### ISSUE TITLE
Error while composer install

### ISSUE THREAD

**Issue by dzulhelmi** [Attendize/Attendize#101]
While i do composer install, its all good until it shows this:

```
Generating autoload files
> php artisan clear-compiled
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log')
#1 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array)
#2 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log')
#4 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(Ref in /home/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738

Fatal error: Uncaught ReflectionException: Class log does not exist in /home/forgemydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log')
#1 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array)
#2 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(697): Illuminate\Container\Container->make('log', Array)
#3 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log')
#4 /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(Ref in /home/forge/mydomain.com/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738
Script php artisan clear-compiled handling the post-install-cmd event returned with an error

                                                                               
  [RuntimeException]                                                           
  Error Output: PHP Fatal error:  Uncaught ReflectionException: Class log doe  
  s not exist in /home/forge/mydomain.com/attendize/vendor/laravel  
  /framework/src/Illuminate/Container/Container.php:738                        
  Stack trace:                                                                 
  #0 /home/forge/mydomain.com/attendize/vendor/laravel/framework/s  
  rc/Illuminate/Container/Container.php(738): ReflectionClass->__construct('l  
  og')                                                                         
  #1 /home/forge/mydomain.com/attendize/vendor/laravel/framework/s  
  rc/Illuminate/Container/Container.php(633): Illuminate\Container\Container-  
  >build('log', Array)                                                         
  #2 /home/forge/mydomain.com/attendize/vendor/laravel/framework/s  
  rc/Illuminate/Foundation/Application.php(697): Illuminate\Container\Contain  
  er->make('log', Array)                                                       
  #3 /home/forge/mydomain.com/attendize/vendor/laravel/framework/s  
  rc/Illuminate/Container/Container.php(853): Illuminate\Foundation\Applicati  
  on->make('log')                                                              
  #4 /home/forge/mydomain.com/attendize/vendor/laravel/framework/s  
  rc/Illuminate/Container/Container.php(808): Illuminate\Container\Container-  
  >resolveClass(Object(Ref in /home/forge/mydomain.com/attendize/v  
  endor/laravel/framework/src/Illuminate/Container/Container.php on line 738   
```

**Comment by dzulhelmi** [comment]
Solved, space in .env file caused the problem.
