### ISSUE TITLE
Admin login suddenly results in 'we'll be back soon'

### ISSUE THREAD

**Issue by MacBadger** [Attendize/Attendize#1028]
Suddenly, without changes, the last few **days** the admin login results in the error page:

"We'll be back soon
We're currently making improvements to our website."

Meanwhile, the ability to purchase seems unaffected.
Any ideas?

v2.4.0

**Comment by MacBadger** [comment]
apologies, I must have hit backspace straight after paste!
Note: '/home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php' DOES exist! Is writable by webserver user also.

`[2022-05-30 11:22:30] production.ERROR: file_put_contents(/home/tickets/Attendize/storage/framework/cache/data/a2/89/a289f5f28b3a64c787ef95388b4d00c410d168cd): failed to open stream: No such file or directory {"exception":"[object] (ErrorException(code: 0): file_put_contents(/home/tickets/Attendize/storage/framework/cache/data/a2/89/a289f5f28b3a64c787ef95388b4d00c410d168cd): failed to open stream: No such file or directory at /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()
#2 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(74): Illuminate\\Filesystem\\Filesystem->put()
#3 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(211): Illuminate\\Cache\\FileStore->put()
#4 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(316): Illuminate\\Cache\\Repository->put()
#5 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Cache/RateLimiter.php(60): Illuminate\\Cache\\Repository->add()
#6 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(57): Illuminate\\Cache\\RateLimiter->hit()
#7 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#8 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#10 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#12 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Session\\Middleware\\StartSession->handle()
#14 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#16 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#18 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then()
#20 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack()
#21 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute()
#22 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute()
#23 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch()
#24 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#25 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#27 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#29 /home/tickets/Attendize/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle()
#31 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#33 /home/tickets/Attendize/app/Http/Middleware/GeneralChecks.php(26): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\GeneralChecks->handle()
#35 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#37 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then()
#39 /home/tickets/Attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#40 /home/tickets/Attendize/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()`

**Comment by MacBadger** [comment]
Somehow, directory ownership had randomly changed last Saturday.
