### ISSUE TITLE
Error in composer install / Update

### ISSUE THREAD

**Issue by clawfire** [Attendize/Attendize#171]
```
Writing lock file
Generating autoload files
> php artisan clear-compiled
[2016-07-26 12:48:43] production.ERROR: exception 'ErrorException' with message 'Missing argument 3 for Illuminate\Session\FileSessionHandler::__construct(), called in /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php on line 12366 and defined' in /Users/tmilan/Personnal/tickets/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php:41
Stack trace:
#0 /Users/tmilan/Personnal/tickets/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(41): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Missing argumen...', '/Users/tmilan/P...', 41, Array)
#1 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(12366): Illuminate\Session\FileSessionHandler->__construct(Object(Illuminate\Filesystem\Filesystem), '/Users/tmilan/P...')
#2 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(12361): Illuminate\Session\SessionManager->createNativeDriver()
#3 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(12462): Illuminate\Session\SessionManager->createFileDriver()
#4 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(12452): Illuminate\Support\Manager->createDriver('file')
#5 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(7839): Illuminate\Support\Manager->driver()
#6 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1347): Illuminate\Session\SessionServiceProvider->Illuminate\Session\{closure}(Object(Illuminate\Foundation\Application), Array)
#7 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1303): Illuminate\Container\Container->build(Object(Closure), Array)
#8 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1865): Illuminate\Container\Container->make('session.store', Array)
#9 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1547): Illuminate\Foundation\Application->make('session.store')
#10 /Users/tmilan/Personnal/tickets/vendor/laravelcollective/html/src/HtmlServiceProvider.php(52): Illuminate\Container\Container->offsetGet('session.store')
#11 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1347): Collective\Html\HtmlServiceProvider->Collective\Html\{closure}(Object(Illuminate\Foundation\Application), Array)
#12 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1303): Illuminate\Container\Container->build(Object(Closure), Array)
#13 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1865): Illuminate\Container\Container->make('form', Array)
#14 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1547): Illuminate\Foundation\Application->make('form')
#15 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(6307): Illuminate\Container\Container->offsetGet('form')
#16 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(6293): Illuminate\Support\Facades\Facade::resolveFacadeInstance('form')
#17 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(6327): Illuminate\Support\Facades\Facade::getFacadeRoot()
#18 /Users/tmilan/Personnal/tickets/app/Helpers/macros.php(16): Illuminate\Support\Facades\Facade::__callStatic('macro', Array)
#19 /Users/tmilan/Personnal/tickets/app/Helpers/macros.php(16): Collective\Html\FormFacade::macro('rawLabel', Object(Closure))
#20 /Users/tmilan/Personnal/tickets/app/Providers/HelpersServiceProvider.php(17): require('/Users/tmilan/P...')
#21 [internal function]: App\Providers\HelpersServiceProvider->boot()
#22 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1248): call_user_func_array(Array, Array)
#23 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1890): Illuminate\Container\Container->call(Array)
#24 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1882): Illuminate\Foundation\Application->bootProvider(Object(App\Providers\HelpersServiceProvider))
#25 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Providers\HelpersServiceProvider), 15)
#26 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1883): array_walk(Array, Object(Closure))
#27 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(2221): Illuminate\Foundation\Application->boot()
#28 /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php(1657): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#29 /Users/tmilan/Personnal/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
#30 /Users/tmilan/Personnal/tickets/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#31 /Users/tmilan/Personnal/tickets/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 {main}



  [ErrorException]
  Missing argument 3 for Illuminate\Session\FileSessionHandler::__construct(), called in /Users/tmilan/Personnal/tickets/bootstrap/cache/compiled.php on line 12366 and defined

Script php artisan clear-compiled handling the post-update-cmd event returned with error code 1
```

**Comment by daveearley** [comment]
Try manually deleting **bootstrap/cache/compiled.php** trying again.

**Comment by clawfire** [comment]
So I'll have to write a deployment script that do that for me before deploying a new version of the app ?  😣

**Comment by clawfire** [comment]
Thanks it solve the issue
