### ISSUE TITLE
error in composer install on heroku

### ISSUE THREAD

**Issue by clawfire** [Attendize/Attendize#172]
```
remote:        Generating optimized autoload files
remote:        > php artisan clear-compiled
remote:        [2016-07-26 21:42:13] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found in /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146
remote:        Stack trace:
remote:        #0 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(114): Illuminate\Foundation\ProviderRepository->createProvider('Barryvdh\\Larave...')
remote:        #1 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(60): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
remote:        #2 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(530): Illuminate\Foundation\ProviderRepository->load(Array)
remote:        #3 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
remote:        #4 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
remote:        #5 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(219): Illuminate\Foundation\Application->bootstrapWith(Array)
remote:        #6 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
remote:        #7 /tmp/build_1f3209f665fecf69cfcc7a78cd9e89bb/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
remote:        #8 {main}
remote:
remote:
remote:
remote:          [Symfony\Component\Debug\Exception\FatalThrowableError]
remote:          Class 'Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider' not found
remote:
remote:
remote:        Script php artisan clear-compiled handling the post-install-cmd event returned with an error
```

Strangely I have no problem in composer update / install in local :/

**Comment by daveearley** [comment]
Does manually removing **bootstrap/compiled.php** and then running `composer update` work?

**Comment by clawfire** [comment]
There's no file named `compiled.php` in `bootstrap`. But there's one in `bootstrap/cache/` in my local env. On the remote on heroku there's not. I run `heroku run "rm bootstrap/cache/compiled.php"` but there's no file like this one. Error still occure.

**Comment by ojas121** [comment]
I'm having the same problem. Have you found a solution?

**Comment by lucidlive** [comment]
For me, simply running "composer update --no-scripts" and then re-pushing worked.
