### ISSUE TITLE
TokenMismatchException on delayed login

### ISSUE THREAD

**Issue by githubertus** [Attendize/Attendize#340]
I was visiting my shop's backend url today, but for some reason I got interrupted - leaving the login dialog box untouched on screen. Two or three hours must have passed until I finally tried to login and getting a "Oops, something ..." message and the exception shown below. After refreshing the page, everything was back to normal.

```
[18-Mar-2017 21:36:39 UTC] [2017-03-18 21:36:39] production.ERROR: exception 'Illuminate\Session\TokenMismatchException' in /bootstrap/cache/compiled.php:3224
Stack trace:
#0 /app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#1 [internal function]: App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#2 /bootstrap/cache/compiled.php(9980): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#4 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#5 /bootstrap/cache/compiled.php(13426): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /bootstrap/cache/compiled.php(9980): call_user_func_array(Array, Array)
#8 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#9 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 /bootstrap/cache/compiled.php(11969): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#12 /bootstrap/cache/compiled.php(9980): call_user_func_array(Array, Array)
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /bootstrap/cache/compiled.php(13165): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 /bootstrap/cache/compiled.php(9980): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /bootstrap/cache/compiled.php(13102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /bootstrap/cache/compiled.php(9980): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /bootstrap/cache/compiled.php(3283): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /bootstrap/cache/compiled.php(9980): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /bootstrap/cache/compiled.php(9965): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /bootstrap/cache/compiled.php(2363): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /bootstrap/cache/compiled.php(2347): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#34 /public/index.php(61): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

```

**Comment by shadywallas** [comment]
That's expected , token will flush from session . 
read more about CSRF protection  
here is a link from laravel https://laravel.com/docs/5.6/csrf

**Comment by ajita-asthana** [comment]
Is there are a solution to this issue?
Did anyone else face it?

**Comment by tux-tn** [comment]
You can leverage session lifetime, it's located in ```config/session.php```

**Comment by jeremyquinton** [comment]
@shadywallas @tux-tn thanks for providing the links and info. This will happen when a session expires. Attendize sessions are configured for 2 hours by default.
