### ISSUE TITLE
email setting error

### ISSUE THREAD

**Issue by kmusicfest** [Attendize/Attendize#480]
whenever I order tickets or doing with sending email, I've got this message

"Whoops!, it looks like the server returned an error. Please try again, or contact the webmaster if the problem persists"

my email setting in .env file is

MAIL_DRIVER=smtp
MAIL_PORT=587
MAIL_ENCRYPTION=tls
MAIL_HOST=smtp.gmail.com
MAIL_FROM_ADDRESS=
MAIL_FROM_NAME=password of my email 
MAIL_PASSWORD=********
MAIL_USERNAME=my email adress

what is wrong with me?
please help me out here

**Comment by jeremyquinton** [comment]
@kmusicfest have you taken a look at the troubleshooting guide might be a permissions issue. 

https://www.attendize.com/troubleshooting.html

Also in your .env file you can set
```APP_DEBUG=true```

and you should get a full error in 
```storage/logs/```

Also try setting the from address in your configuration.

**Comment by samdb** [comment]
I would try putting quotes around things as a first step. I believe Laravel requires strings to be in quotes now.

MAIL_HOST="smtp.gmail.com"

**Comment by kmusicfest** [comment]
I believe that I have set it all you mentioned above.

Setting permissions correctly on folders 

and App_DEBUG=true changed already.

also strings in the quotes

here's my log file

[2018-10-02 12:05:01] production.INFO: Firing the event  
[2018-10-02 12:05:01] production.INFO: Begin Processing Order: OSIT4210  
[2018-10-02 12:05:01] production.INFO: Generating ticket: #OSIT4210  
[2018-10-02 12:05:01] production.INFO: {"id":25,"account_id":1,"order_status_id":1,"created_at":"2018-10-02 12:05:00","updated_at":"2018-10-02 12:05:00","deleted_at":null,"first_name":"hyouk","last_name":"kwon","email":"hyouk1945@gmail.com","ticket_pdf_path":null,"order_reference":"OSIT4210","transaction_id":null,"discount":"0.00","booking_fee":"0.00","organiser_booking_fee":"0.00","order_date":null,"notes":null,"is_deleted":0,"is_cancelled":0,"is_partially_refunded":0,"is_refunded":0,"amount":"0.00","amount_refunded":null,"event_id":1,"payment_gateway_id":null,"is_payment_received":1,"taxamt":0}  
[2018-10-02 12:05:01] production.ERROR: file_get_contents(/usr/share/nginx/html/attendize/public/user_content/event_images/event_image-fd85aecc81059d13b2680f2475f4bb3b.jpg): failed to open stream: No such file or directory {"userId":1,"email":"hyouk1945@gmail.com","exception":"[object] (ErrorException(code: 0): file_get_contents(/usr/share/nginx/html/attendize/public/user_content/event_images/event_image-fd85aecc81059d13b2680f2475f4bb3b.jpg): failed to open stream: No such file or directory at /usr/share/nginx/html/attendize/app/Jobs/GenerateTicket.php:66)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'file_get_conten...', '/usr/share/ngin...', 66, Array)
#1 /usr/share/nginx/html/attendize/app/Jobs/GenerateTicket.php(66): file_get_contents('/usr/share/ngin...')
#2 [internal function]: App\\Jobs\\GenerateTicket->handle()
#3 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#4 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#8 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\GenerateTicket))
#9 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\GenerateTicket))
#10 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#11 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\GenerateTicket), false)
#12 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#13 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()
#14 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(184): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\GenerateTicket))
#15 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(160): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\GenerateTicket))
#16 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\GenerateTicket))
#17 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\GenerateTicket))
#18 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(393): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#19 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php(147): dispatch(Object(App\\Jobs\\GenerateTicket))
#20 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(104): App\\Jobs\\ProcessGenerateAndSendTickets->dispatchNextJobInChain()
#21 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(53): Illuminate\\Queue\\CallQueuedHandler->ensureNextJobInChainIsDispatched(Object(App\\Jobs\\ProcessGenerateAndSendTickets))
#22 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#23 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()
#24 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(184): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\ProcessGenerateAndSendTickets))
#25 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(160): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\ProcessGenerateAndSendTickets))
#26 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\ProcessGenerateAndSendTickets))
#27 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(112): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\ProcessGenerateAndSendTickets))
#28 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingChain.php(43): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#29 /usr/share/nginx/html/attendize/app/Listeners/OrderCompletedListener.php(45): Illuminate\\Foundation\\Bus\\PendingChain->dispatch()
#30 [internal function]: App\\Listeners\\OrderCompletedListener->handle(Object(App\\Events\\OrderCompletedEvent))
#31 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Events/CallQueuedListener.php(86): call_user_func_array(Array, Array)
#32 [internal function]: Illuminate\\Events\\CallQueuedListener->handle(Object(Illuminate\\Foundation\\Application))
#33 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#34 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#35 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#36 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Container/Container.php(564): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#37 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#38 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#39 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Events\\CallQueuedListener))
#40 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#41 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Illuminate\\Events\\CallQueuedListener), false)
#42 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(83): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#43 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()
#44 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(37): Illuminate\\Queue\\SyncQueue->push(Object(Illuminate\\Events\\CallQueuedListener), '', NULL)
#45 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(485): Illuminate\\Queue\\Queue->pushOn(NULL, Object(Illuminate\\Events\\CallQueuedListener))
#46 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(444): Illuminate\\Events\\Dispatcher->queueHandler('App\\\\Listeners\\\\O...', 'handle', Array)
#47 [internal function]: Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}(Object(App\\Events\\OrderCompletedEvent))
#48 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(379): call_user_func_array(Object(Closure), Array)
#49 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(209): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('App\\\\Events\\\\Orde...', Array)
#50 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(476): Illuminate\\Events\\Dispatcher->dispatch('App\\\\Events\\\\Orde...')
#51 /usr/share/nginx/html/attendize/app/Http/Controllers/EventCheckoutController.php(692): event(Object(App\\Events\\OrderCompletedEvent))
#52 /usr/share/nginx/html/attendize/app/Http/Controllers/EventCheckoutController.php(463): App\\Http\\Controllers\\EventCheckoutController->completeOrder('1')
#53 [internal function]: App\\Http\\Controllers\\EventCheckoutController->postCreateOrder(Object(Illuminate\\Http\\Request), '1')
#54 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#55 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('postCreateOrder', Array)
#56 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\EventCheckoutController), 'postCreateOrder')
#57 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#58 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(679): Illuminate\\Routing\\Route->run()
#59 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /usr/share/nginx/html/attendize/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationViewPath.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationViewPath->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /usr/share/nginx/html/attendize/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationRedirectFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /usr/share/nginx/html/attendize/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Mcamara\\LaravelLocalization\\Middleware\\LocaleSessionRedirect->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#71 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#72 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#73 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Router.php(611): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#74 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#75 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#76 /usr/share/nginx/html/attendize/app/Http/Middleware/GeneralChecks.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#77 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): app\\Http\\Middleware\\GeneralChecks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#78 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#79 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#80 /usr/share/nginx/html/attendize/app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#81 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#82 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#83 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#84 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#85 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#86 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#87 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#88 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#89 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#90 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#91 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#92 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#93 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#94 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#95 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#96 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#97 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#98 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#99 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#100 /usr/share/nginx/html/attendize/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#101 /usr/share/nginx/html/attendize/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#102 {main}
"}

**Comment by samdb** [comment]
This error shows the ticket is failing to be generated because your custom image (logo?) can't be found.

**Comment by modifiedcontent** [comment]
I get this 'Whoops!' error with the Widget HTML Embed Code version of the ticket registration form, but if I use the normal (ugly) event url page generated by the application, registration works fine; payment goes through via the Stripe gateway, confirmation emails get send, etc. 

So in my case there are no problems with either email setup, pdf generation or the payment gateway. The embed widget seems to cause the problem. 

I don't get any error logs with App_DEBUG=true; nothing shows up in /storage/logs or error_log. So I'm not sure how to troubleshoot this embed problem. Is it some path mismatch? Javascript conflicts? Something else?

The embed widget worked fine on the same websites/server two years ago, before "The Event" put my events business on hold. What changed? Anything else I should update? I already updated to Attendize-2.6.0.
