### ISSUE TITLE
Order page generating an error

### ISSUE THREAD

**Issue by lporcheron** [Attendize/Attendize#59]
Hello,

I have installed the 0.5.0 version of Attendize. I have created an event, a (free) ticket and when I book the ticket or try to access the order, I got the following error:

```
[2016-03-24 00:22:50] production.ERROR: exception 'ReflectionException' with message 'Class App\Http\Controllers\Request does not exist' in /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php:7171
Stack trace:
#0 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7171): ReflectionParameter->getClass()
#1 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7162): Illuminate\Routing\ControllerDispatcher->transformDependency(Object(ReflectionParameter), Array, Array)
#2 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7156): Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies(Array, Object(ReflectionMethod))
#3 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(8912): Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies(Array, Object(App\Http\Controllers\EventOrdersController), 'showOrders')
#4 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(8893): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\EventOrdersController), Object(Illuminate\Routing\Route), 'showOrders')
#5 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9555): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9537): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(8894): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(8879): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\EventOrdersController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'showOrders')
#11 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7833): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\Http\Contro...', 'showOrders')
#12 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7804): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#13 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7457): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9555): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /srv/www/events.example.com/attendize-0.5.0/app/Http/Middleware/FirstRunMiddleware.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: app\Http\Middleware\FirstRunMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#19 /srv/www/events.example.com/attendize-0.5.0/app/Http/Middleware/Authenticate.php(47): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#22 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9537): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7458): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7446): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(7431): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(2303): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9555): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /srv/www/events.example.com/attendize-0.5.0/app/Http/Middleware/GeneralChecks.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: app\Http\Middleware\GeneralChecks->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#33 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(2927): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /srv/www/events.example.com/attendize-0.5.0/app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: App\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#37 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(12875): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#40 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(11498): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#43 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(12616): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#46 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(12555): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#49 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(2977): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9547): call_user_func_array(Array, Array)
#52 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(9537): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(2250): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 /srv/www/events.example.com/attendize-0.5.0/bootstrap/cache/compiled.php(2233): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 /srv/www/events.example.com/attendize-0.5.0/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}  
```

I also get an error when I try to order a ticket.
My tickets are free, I don't have any payment gateway defined.

Attendize is installed on a standard Ubuntu 14.04 with PHP 5.5.9, apache and MySQL coming from Ubuntu.

**Comment by daveearley** [comment]
This was caused by a missing use statement in the **app/Http/Controllers/EventOrdersController.php** file. Replacing the contents of that file with the updated version should fix the issue. You can get the file here: https://raw.githubusercontent.com/Attendize/Attendize/master/app/Http/Controllers/EventOrdersController.php

Cheers

**Comment by lporcheron** [comment]
Thank you, works great now!
