### ISSUE TITLE
Can't send email, leading to frontend crash (but payment collected)

### ISSUE THREAD

**Issue by clawfire** [Attendize/Attendize#650]
Ok I have a weird issue I didn't seen before but not sure if it's completly new because of ... something or due to an update (than I havent done in a while) or due to update in PHP (now 7.X) ... but when a client try to checkout, the PDF ticket is generated but when trying to send them, the app crashed. The error displayed in the front end but clients are a bit confused :/ They don't know if they have their ticket or not and some would try again and again ... and been charged multiple times. 

```
[2019-06-10 20:04:32] production.INFO: Sending ticket to: [REDACTED]  
[2019-06-10 20:04:32] production.ERROR: Expected response code 220 but got an empty response {"userId":1,"exception":"[object] (Swift_TransportException(code: 0): Expected response code 220 but got an empty response at /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:445)
[stacktrace]
#0 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(358): Swift_Transport_AbstractSmtpTransport->assertResponseCode('', Array)
#1 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(147): Swift_Transport_AbstractSmtpTransport->readGreeting()
#2 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/SendmailTransport.php(50): Swift_Transport_AbstractSmtpTransport->start()
#3 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(65): Swift_Transport_SendmailTransport->start()
#4 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(484): Swift_Mailer->send(Object(Swift_Message), Array)
#5 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(259): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#6 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Mail\\Mailer->send('Mailers.TicketM...', Array, Object(Closure))
#7 /srv/data/web/vhosts/tickets.bears.lu/htdocs/app/Mailers/AttendeeMailer.php(32): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#8 /srv/data/web/vhosts/tickets.bears.lu/htdocs/app/Jobs/SendAttendeeTicket.php(36): App\\Mailers\\AttendeeMailer->sendAttendeeTicket(Object(App\\Models\\Attendee))
#9 [internal function]: App\\Jobs\\SendAttendeeTicket->handle(Object(App\\Mailers\\AttendeeMailer))
#10 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#11 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#13 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Container/Container.php(580): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#14 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#15 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\SendAttendeeTicket))
#16 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\SendAttendeeTicket))
#17 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#18 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\SendAttendeeTicket), false)
#19 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(86): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#20 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()
#21 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(184): Illuminate\\Queue\\SyncQueue->push(Object(App\\Jobs\\SendAttendeeTicket))
#22 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(160): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(App\\Jobs\\SendAttendeeTicket))
#23 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(App\\Jobs\\SendAttendeeTicket))
#24 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\\Bus\\Dispatcher->dispatch(Object(App\\Jobs\\SendAttendeeTicket))
#25 /srv/data/web/vhosts/tickets.bears.lu/htdocs/app/Http/Controllers/EventAttendeesController.php(850): App\\Http\\Controllers\\Controller->dispatch(Object(App\\Jobs\\SendAttendeeTicket))
#26 [internal function]: App\\Http\\Controllers\\EventAttendeesController->postResendTicketToAttendee(Object(Illuminate\\Http\\Request), '597')
#27 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#28 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('postResendTicke...', Array)
#29 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\EventAttendeesController), 'postResendTicke...')
#30 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#31 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#32 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /srv/data/web/vhosts/tickets.bears.lu/htdocs/app/Http/Middleware/FirstRunMiddleware.php(34): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): app\\Http\\Middleware\\FirstRunMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /srv/data/web/vhosts/tickets.bears.lu/htdocs/app/Http/Middleware/Authenticate.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationViewPath.php(33): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationViewPath->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LaravelLocalizationRedirectFilter.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LaravelLocalizationRedirectFilter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/mcamara/laravel-localization/src/Mcamara/LaravelLocalization/Middleware/LocaleSessionRedirect.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Mcamara\\LaravelLocalization\\Middleware\\LocaleSessionRedirect->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#51 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#52 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#53 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#54 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#55 /srv/data/web/vhosts/tickets.bears.lu/htdocs/app/Http/Middleware/GeneralChecks.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#56 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): app\\Http\\Middleware\\GeneralChecks->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#57 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /srv/data/web/vhosts/tickets.bears.lu/htdocs/app/Http/Middleware/VerifyCsrfToken.php(24): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#60 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#67 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#68 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#69 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#70 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#71 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#72 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#73 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#74 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#75 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#76 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#77 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#78 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#79 /srv/data/web/vhosts/tickets.bears.lu/htdocs/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#80 /srv/data/web/vhosts/tickets.bears.lu/htdocs/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#81 {main}
"} 
```

**Comment by clawfire** [comment]
Ok seems the mailer doesn't accept local connection anymore. I switched to a email server and it works. Weird.
